"""Generate appendix tables (per-domain, per-backbone, per-horizon)
directly from the locked CSV summaries.  Output goes to
``paper/tab_appendix_*.tex`` and is included from ``appendix.tex``.

Run with:
    /home/karthik/miniconda3/envs/aurora/bin/python \
        paper/figures/make_appendix_tables.py
"""
from __future__ import annotations
import sys
from pathlib import Path
import pandas as pd

PROJECT = Path(__file__).resolve().parents[2]
SUM = PROJECT / "summaries"
DEEP = SUM / "deep"
OUT = PROJECT / "paper"

# Column orderings consistent with the main paper tables.
COND_ORDER = [
    "C1_original", "C3_shuffled", "C4_crossdomain", "C8_oracle",
    "C9_zero_priors", "C2_empty", "C5_constant", "C6_unimodal",
]
COND_TEX = {
    "C1_original":     r"\Cone{}",
    "C2_empty":        r"\Ctwo{}",
    "C3_shuffled":     r"\Cthree{}",
    "C4_crossdomain":  r"\Cfour{}",
    "C5_constant":     r"\Cfive{}",
    "C6_unimodal":     r"\Csix{}",
    "C8_oracle":       r"\Ceight{}",
    "C9_zero_priors":  r"\Cnine{}",
}
DOMAINS = ["Agriculture", "Climate", "Economy", "Energy", "Environment",
           "Health", "Security", "SocialGood", "Traffic"]

LATEX_HEADER = r"""% AUTO-GENERATED by paper/figures/make_appendix_tables.py.
% Do not edit by hand; rerun the script after changing summaries.
"""


def fmt_mse(v: float, ref: float | None = None) -> str:
    """Render an MSE value, optionally with a percent-delta vs reference."""
    if pd.isna(v):
        return r"\textendash"
    if ref is None or pd.isna(ref) or ref == 0:
        return f"${v:.3f}$"
    pct = 100 * (v - ref) / ref
    sign = "+" if pct >= 0 else ""
    return f"${v:.3f}$\\,\\scriptsize({sign}{pct:.2f}\\%)"


def latex_escape(s: str) -> str:
    """Escape characters that have special meaning in LaTeX (no math)."""
    return (s.replace("\\", r"\textbackslash{}")
             .replace("_", r"\_")
             .replace("&", r"\&")
             .replace("%", r"\%")
             .replace("#", r"\#"))


def per_backbone_table(model: str, csv_path: Path) -> str:
    df = pd.read_csv(csv_path).set_index("condition")
    df = df.reindex(COND_ORDER).dropna(how="all")

    backbones = [c for c in df.columns if c != "condition"]
    if not backbones:
        return ""

    refs = df.loc["C1_original", backbones]
    rows = []
    for cond in df.index:
        row = [COND_TEX[cond]]
        for bb in backbones:
            v = df.loc[cond, bb]
            ref = refs[bb]
            row.append(fmt_mse(v, ref if cond != "C1_original" else None))
        rows.append(" & ".join(row) + r" \\")

    cols = "l" + "r" * len(backbones)
    head = " & ".join(["\\textbf{Cond.}"] + [f"\\textbf{{{bb}}}" for bb in backbones])
    body = "\n".join(rows)
    pretty_model = {"aurora": r"\Aurora{}", "mmtsflib": r"\MMTSF{}",
                    "tats": r"\TaTS{}"}[model]
    src_path = latex_escape(str(csv_path.relative_to(PROJECT)))
    return rf"""
\begin{{table}}[h]
\centering
\small
\setlength{{\tabcolsep}}{{4pt}}
\renewcommand{{\arraystretch}}{{1.16}}
\caption{{Per-backbone mean MSE on \TimeMMD{{}} for {pretty_model}.
Each cell is the mean over $9$ domains $\times\, 4$ horizons
$\times\, 3$ seeds.  $\Delta\%$ vs.\ \Cone{{}} reported in
parentheses.  Source: \texttt{{{src_path}}}.}}
\label{{tab:perbb_{model}}}
\begin{{tabular}}{{{cols}}}
\toprule
{head} \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def per_domain_table(model: str, csv_path: Path) -> str:
    df = pd.read_csv(csv_path).set_index("condition")
    df = df.reindex(COND_ORDER).dropna(how="all")
    cols_present = [d for d in DOMAINS if d in df.columns]

    refs = df.loc["C1_original", cols_present]
    rows = []
    for cond in df.index:
        row = [COND_TEX[cond]]
        for dom in cols_present:
            v = df.loc[cond, dom]
            ref = refs[dom]
            row.append(fmt_mse(v, ref if cond != "C1_original" else None))
        rows.append(" & ".join(row) + r" \\")

    cols = "l" + "r" * len(cols_present)
    head = " & ".join(["\\textbf{Cond.}"] + [
        f"\\rotatebox{{60}}{{\\textbf{{{d[:7]}}}}}" for d in cols_present
    ])
    body = "\n".join(rows)
    pretty_model = {"aurora": r"\Aurora{}", "mmtsflib": r"\MMTSF{}",
                    "tats": r"\TaTS{}"}[model]
    src_path = latex_escape(str(csv_path.relative_to(PROJECT)))
    return rf"""
\begin{{table*}}[h]
\centering
\footnotesize
\setlength{{\tabcolsep}}{{2.5pt}}
\renewcommand{{\arraystretch}}{{1.14}}
\caption{{Per-domain mean MSE on \TimeMMD{{}} for {pretty_model}.
Each cell is the mean over $4$ horizons $\times\, 3$ seeds (and $3$
backbones for trained methods).  $\Delta\%$ vs.\ \Cone{{}} in
parentheses.  Source: \texttt{{{src_path}}}.}}
\label{{tab:perdom_{model}}}
\begin{{adjustbox}}{{max width=\textwidth,center}}
\begin{{tabular}}{{{cols}}}
\toprule
{head} \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{adjustbox}}
\end{{table*}}
"""


def horizon_averaged_table() -> str:
    """Per-horizon ladder for each model.

    Uses per_cell.csv directly because the convenience
    horizon_averaged.csv aggregates over pred_len.  Aggregation here
    averages over (domain, seed, backbone) for each (model, condition,
    pred_len) tuple.
    """
    csv_path = SUM / "per_cell.csv"
    df = pd.read_csv(csv_path)

    out_blocks = []
    for model in ["aurora", "mmtsflib", "tats"]:
        sub = df[(df["model"] == model) & (df["success"] == True)]
        if sub.empty:
            continue
        pivot = sub.pivot_table(
            index="condition", columns="pred_len", values="mse",
            aggfunc="mean")
        pivot = pivot.reindex(COND_ORDER).dropna(how="all")
        pred_lens = sorted(pivot.columns.tolist())
        refs = pivot.loc["C1_original"] if "C1_original" in pivot.index else None
        rows = []
        for cond in pivot.index:
            row = [COND_TEX[cond]]
            for pl in pred_lens:
                v = pivot.loc[cond, pl]
                ref = refs[pl] if refs is not None else None
                row.append(fmt_mse(v, ref if cond != "C1_original" else None))
            rows.append(" & ".join(row) + r" \\")
        cols = "l" + "r" * len(pred_lens)
        head = " & ".join(["\\textbf{Cond.}"] + [
            f"$H={pl}$" for pl in pred_lens
        ])
        body = "\n".join(rows)
        pretty_model = {"aurora": r"\Aurora{}", "mmtsflib": r"\MMTSF{}",
                        "tats": r"\TaTS{}"}[model]
        out_blocks.append(rf"""
\begin{{table*}}[h]
\centering
\footnotesize
\setlength{{\tabcolsep}}{{2.5pt}}
\renewcommand{{\arraystretch}}{{1.14}}
\caption{{Per-horizon mean MSE for {pretty_model} on \TimeMMD{{}}.
Aggregated over domains, seeds, and (for trained methods)
backbones; $\Delta\%$ vs.\ \Cone{{}} at the same horizon in
parentheses.}}
\label{{tab:perhz_{model}}}
\begin{{adjustbox}}{{max width=\textwidth,center}}
\begin{{tabular}}{{{cols}}}
\toprule
{head} \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{adjustbox}}
\end{{table*}}
""")
    return "\n".join(out_blocks)


def main() -> None:
    out_dir = OUT
    out_dir.mkdir(parents=True, exist_ok=True)

    # Per-backbone tables (3 trained models + Aurora's single column).
    pb_chunks = [LATEX_HEADER]
    for model, fname in [("aurora", "per_backbone_aurora.csv"),
                          ("mmtsflib", "per_backbone_mmtsflib.csv"),
                          ("tats", "per_backbone_tats.csv")]:
        path = SUM / fname
        if path.exists():
            pb_chunks.append(per_backbone_table(model, path))
    (out_dir / "tab_appendix_perbackbone.tex").write_text(
        "".join(pb_chunks))

    # Per-domain tables.
    pd_chunks = [LATEX_HEADER]
    for model, fname in [("aurora", "per_domain_aurora.csv"),
                          ("mmtsflib", "per_domain_mmtsflib.csv"),
                          ("tats", "per_domain_tats.csv")]:
        path = SUM / fname
        if path.exists():
            pd_chunks.append(per_domain_table(model, path))
    (out_dir / "tab_appendix_perdomain.tex").write_text(
        "".join(pd_chunks))

    # Per-horizon table (depends on the deep/horizon_averaged.csv schema).
    ph = horizon_averaged_table()
    (out_dir / "tab_appendix_perhorizon.tex").write_text(LATEX_HEADER + ph)

    print("wrote tab_appendix_perbackbone.tex")
    print("wrote tab_appendix_perdomain.tex")
    print("wrote tab_appendix_perhorizon.tex")


if __name__ == "__main__":
    main()
