"""Generate the main results table -- multirow format with bold/underline
highlighting of the lowest two MSEs per (model, domain) cell.

Output: paper/tab_main.tex.

Style template (from the user):

    Metric / Condition | Domain1 | Domain2 | ... | Avg
    -- model 1 group: 7 conditions, multirow on model name
    -- model 2 group: 7 conditions
    -- model 3 group: 7 conditions

Run with:
    /home/karthik/miniconda3/envs/aurora/bin/python \
        paper/figures/make_main_table.py
"""
from __future__ import annotations
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT = Path(__file__).resolve().parents[2]
SUM = PROJECT / "summaries"
OUT = PROJECT / "paper" / "tab_main.tex"

# Conditions to include (drop C7_null, redundant with C5_constant).
COND_ORDER = [
    "C1_original", "C3_shuffled", "C4_crossdomain", "C8_oracle",
    "C9_zero_priors", "C2_empty", "C5_constant", "C6_unimodal",
]
COND_LABEL = {
    "C1_original":     r"C1 Original",
    "C2_empty":        r"C2 Empty",
    "C3_shuffled":     r"C3 Shuffled",
    "C4_crossdomain":  r"C4 Cross-domain",
    "C5_constant":     r"C5 Constant",
    "C6_unimodal":     r"C6 Unimodal",
    "C8_oracle":       r"C8 Oracle",
    "C9_zero_priors":  r"C9 Zero-priors",
}

# Short-form domain headers in the same order as the TaTS main table.
DOMAINS = ["Agriculture", "Climate", "Economy", "Energy", "Environment",
           "Health", "Security", "SocialGood", "Traffic"]
DOMAIN_SHORT = {
    "Agriculture": "Agri", "Climate": "Clim", "Economy": "Econ",
    "Energy": "Ener",       "Environment": "Envi", "Health": "Heal",
    "Security": "Secu",     "SocialGood": "SocG",  "Traffic": "Traf",
}

MODELS = [
    ("aurora",   r"\textsc{Aurora}",  "per_domain_aurora.csv"),
    ("mmtsflib", r"\textsc{MM-TSFlib}", "per_domain_mmtsflib.csv"),
    ("tats",     r"\textsc{TaTS}",    "per_domain_tats.csv"),
]


def fmt_value(v: float, rank: int) -> str:
    """Format an MSE value, bolding rank=1 and underlining rank=2."""
    if pd.isna(v):
        return r"\,--\,"
    # Choose precision based on magnitude so we get nice alignment.
    if abs(v) >= 100:
        s = f"{v:.1f}"
    elif abs(v) >= 10:
        s = f"{v:.2f}"
    else:
        s = f"{v:.3f}"
    if rank == 1:
        return r"\best{" + s + r"}"
    if rank == 2:
        return r"\second{" + s + r"}"
    return s


def model_block(model_id: str, model_label: str, csv_name: str) -> str:
    df = pd.read_csv(SUM / csv_name).set_index("condition")
    df = df.reindex(COND_ORDER).dropna(how="all")
    domain_cols = [d for d in DOMAINS if d in df.columns]
    sub = df[domain_cols].copy()
    sub["Avg"] = sub.mean(axis=1)
    cols = domain_cols + ["Avg"]

    # Compute per-column rank: 1 = lowest MSE, 2 = second lowest, etc.
    ranks = pd.DataFrame(index=sub.index, columns=cols, dtype=int)
    for c in cols:
        order = sub[c].rank(method="min", ascending=True).fillna(99).astype(int)
        ranks[c] = order

    n_rows = len(sub)
    rows_tex = []
    for i, cond in enumerate(sub.index):
        first = (i == 0)
        prefix = (rf"\multirow{{{n_rows}}}{{*}}{{{model_label}}}"
                  if first else "")
        cells = [fmt_value(sub.loc[cond, c], ranks.loc[cond, c]) for c in cols]
        row = " & ".join([prefix, COND_LABEL[cond]] + cells) + r" \\"
        rows_tex.append(row)
    return "\n".join(rows_tex)


def main() -> None:
    domain_short = [DOMAIN_SHORT[d] for d in DOMAINS]
    n_dom = len(DOMAINS)
    col_spec = "ll " + "c" * n_dom + " c"
    head = " & ".join([
        r"\textbf{Model}", r"\textbf{Condition}",
        *[rf"\textbf{{{d}}}" for d in domain_short],
        r"\textbf{Avg}",
    ])

    blocks = []
    for model_id, label, csv_name in MODELS:
        blocks.append(model_block(model_id, label, csv_name))

    body = ("\n\\midrule\n").join(blocks)

    tex = rf"""% AUTO-GENERATED by paper/figures/make_main_table.py.
% Format: model x condition rows, domain columns + Avg.
% Highlight: \best{{}} = bold = lowest MSE per column within each model;
%            \second{{}} = underline = second lowest.
\begin{{table*}}[t]
\centering
\caption{{\textbf{{Main results.}} Mean test MSE on \TimeMMD{{}} per
$(\text{{model}}, \text{{condition}}, \text{{domain}})$, averaged
across $4$ horizons, $3$ seeds, and (for trained methods) $3$ canonical
backbones (DLinear, Informer, iTransformer).
\textbf{{Bold}} marks the lowest MSE per (model$\times$column);
\underline{{underline}} marks the second lowest.  The column \textbf{{Avg}}
is the cross-domain mean.  \Cnine{{}}, \Ctwo{{}}, and \Cfive{{}} are the
\emph{{prior-zeroed}} conditions; \Cthree{{}}, \Cfour{{}}, and \Ceight{{}}
are the \emph{{text-only}} perturbations; see \cref{{tab:perturbations}}
for the formal definitions.}}
\label{{tab:main}}
\small
\setlength{{\tabcolsep}}{{4pt}}
\renewcommand{{\arraystretch}}{{1.12}}
\begin{{adjustbox}}{{max width=\textwidth,center}}
\begin{{tabular}}{{{col_spec}}}
\toprule
{head} \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{adjustbox}}
\end{{table*}}
"""
    OUT.write_text(tex)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
